### ISSUE TITLE
Assign internal reviewers

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#307]
On a section by section basis, see the list below. The paper audit #304 needs to be done first (so we know what we are reviewing).

### Proposed Internal Reviewers

* [x] Preface: Beth #425
* [x] 1. Introduction: Michael S #421
* [x] 2. Cadence Experiments: 
  * [x] Baseline cadence: Ashish #422 
  * [x] Alternative strategies: Will C #423 
  * [x] Rolling Cadence: Eric G #424 
* [x] 3. Solar System: JJ Kavelaars, plus possibly Mike Solontoi too #426 
* [x] 4. The Galaxy: Mike L #430 
  * [x] Disk: Eric B #428 
  * [x] Astrometry: David N #429
* [x] 5. Variable Objects: Phil #451
  * [x] Cepheids: Steve #417 
  * [x] Multi-periodic pulsating variables: Steve #418
  * [x] Young stars: Steve #419 ( See also #321 )
* [x] 6. Eruptive and Explosive Transients: Michelle #436 
  * [x] Young transients: Ashish #432 
  * [x] SNe: Jeonghee #433 
  * [x] GRBs: Peter K #434 
  * [x] GWs: Marcella #435 
* [x] 7. The Magellanic Clouds: Phil #184 
* [x] 8. AGN: Lucianne #427 
  * [x] Census: Lynne #437 
  * [x] Intrinsic Disk Variability: Phil #438 
  * [x] Microlensing: George Chartas #439 
* [x] 9. Cosmology: 
  * [x] LSS: Josh #443 
  * [x] WL: Jason Rhodes #444 
  * [x] PZ: Phil #441 
  * [x] SNe: Stefano #445 
  * [x] Time delays: Rahul #446 
* [x] 10. Special Surveys: Peter Y 
  * [x] Short exposures
  * [x] Magellanic Clouds: Phil as part of #184 
  * [x] Solar System mini-surveys
* [x] 11. Synergy with WFIRST: 
  * [x] WL: Tony #448 
  * [x] Supernovae: Rahul #449 
  * [x] Microlensing person: Mike L #450

**Comment by ebellm** [comment]
I'll volunteer to help with variable objects and/or the Milky Way.

**Comment by fedhere** [comment]
can we recommend people or fields for our chapters? i think transients would be best reviewed by someone from MW and cosmology, given the overlap

**Comment by drphilmarshall** [comment]
Please do! That would be most helpful.

**Comment by AshishMahabal** [comment]
I will be looking through transients as well.
Eric, thanks for offering to look through the chapter on variables.

**Comment by MichelleLochner** [comment]
@drphilmarshall do you want to list some general guidelines for what we should be focussing on and thinking about as we review a section? This is slightly different from refereeing a standard journal article.

**Comment by drphilmarshall** [comment]
Alright! All sections are now assigned to reviewers. Looking forward to seeing what they all come up with by June 3rd.
