### ISSUE TITLE
Finishing the v1.0 White Paper, editorial meeting Weds Aug 3rd, 0800 PDT

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#483]
Dear @LSSTScienceCollaborations/observing-strategy-white-paper-editors and @LSSTScienceCollaborations/observing-strategy-white-paper-contributors : 

Thank you all for your reviews and edits and patience during what has turned out to be a more extended review period than originally planned!  @bethwillman , @ivezic and I just met to discuss the white paper, having surveyed it's post-review state. There's a ton of good stuff in the paper, as a result of your hard work! However, we do still have a way to go before v1.0 is ready to be posted on the arxiv. Read on! :-)

Below are our high-level editorial comments, which will need addressing before we put the white paper before the LSST pub board. I think they will make sense to you, given how familiar you all are with the paper! Please do digest them thoughtfully; I will also make separate issues tasking us with responding to them. I'll also start a separate thread about planning for the Tucson meeting, which is coming up fast now, and should be a good opportunity to wrap up the remaining loose ends. I think it would be useful to meet by video a couple of weeks before then, to assess the white paper and finalize our meeting plans: if you would like to join (and I expect the chapter editors will want to, at least!), please mark your calendars: **Weds August 3rd at 0800 PDT** is the only time that all three of Beth, Zeljko and I can make it , so that's our meeting time :-)

Thanks again for all your efforts so far! This paper of ours represents a very valuable activity: now we must make it as useful as possible :-)  Comments welcome, as always!

Cheers

Phil

### High-level Editorial Comments

Beth Willman & Phil Marshall

Reading the WP, it seems clear that what we are writing here is very similar to a *book of conference proceedings*:  we are reporting on a collection of ongoing investigations being carried out semi-independently by a research community, and we plan to write peer-reviewed papers on these investigations in the end. Re-framing the white paper in these terms will help our readers make sense of the white paper as a whole. This is a new thought, made possible by your bringing together of the white paper in the last couple of months - and it has implications.

In many parts of the white paper the general standard of presentation does not meet that of a conference proceedings, but it perhaps ought to. Examples of simple fixes needed in various places include: 
* [x] Making figures legible #486 
* [x] Improving figure captions to explain the figure properly #487 
* [x] Including citations #490 
* [x] using the terminology of the field consistently (eg "metric" and "figure of merit", "cadence" vs "observing strategy" vs "OpSim output", and so on) #488 
* [x] eg "we" should mean "we section authors" everywhere it appears, unless stated otherwise #489  

There are sections of the paper whose authors might well deem not ready for presentation at a conference and then publication in the proceedings. This lack of readiness falls into two categories:

1) Many science sections do not have clearly laid out conclusions, of the kind that the LSST Project Science Team would be interested to read. The PST is really our primary audience: it would be great to attract more scientists to come and take part in exploring LSST's observing strategy, but ultimately we are doing these cadence investigations to *inform the Project.* Zeljko has a list of questions he would like to know the answers to: if each science section provided answers to at least some of them, that would make the paper much more interesting for him (and by extension, everyone else!)  These conclusions then need propagating into an executive summary at the start of every chapter, to improve both the readability and the impact of the paper.
* [x] Get list of questions from Zeljko #485 
* [x] Answer questions in every science section #494
* [x] Summarize conclusions in Executive Summary #495

2) There are places where there is qualitative text supporting the concept of a metric or figure or merit, but no actual calculations or results are presented.  Sometimes this supporting text includes a detailed roadmap for how to calculate the relevant quantities and sometimes not. Reading the white paper as a proceedings, we'd suggest that in the cases where there is no MAF calculated result, the supporting text be placed in the Future Work section at the end of the chapter.  The qualitative conclusions that can be derived in these cases could then still be included in the executive summary of the chapter.
* [x] Move some sections to "Further Work" #491 

Implementing the above changes should raise the standard of the white paper considerably. They involve a number of lateral, global editing tasks, of the form "go through the whole paper, fixing all instances of X" - and any individual task need not be too onerous.
* [x] Issue all editorial tasks

**Comment by egawiser** [comment]
All sounds good - but do you mean Monday, August 8, 8AM PDT or Wednesday, August 10, 8AM PDT?

**Comment by drphilmarshall** [comment]
Dammit. One day I will craft the perfect email. I meant **Wednesday August 3rd, 0800 PDT** - to give two weeks before the Tucson meeting. I'll edit the epic above. Thanks!

**Comment by MichelleLochner** [comment]
@drphilmarshall I'm away on the third so can't attend the telecon... Please post minutes after the meeting!

**Comment by lmwalkowicz** [comment]
Shoot, I am in the data science fellowship sessions on the 3rd. Please do post minutes @drphilmarshall!

**Comment by drphilmarshall** [comment]
Dear all,

Don't forget, we are meeting tomorrow (Wednesday August 3rd) at 0800 PDT, to discuss 1) the work needed to finish the v1.0 white paper and 2) the upcoming Tucson meeting. Please review the [editorial comments](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/483#issue-165851896) from @bethwillman and me, and @ivezic 's [10 questions for every science case](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/485#issuecomment-235086316) and come prepared with any questions you have about this.  We're discussing possible contributed plenary talks over in issue #484 and will touch on these and also our planned hack session too. We'll meet in the usual LSST Google hangout, provided it's available - Zeljko? And we'll use [this Google doc](https://docs.google.com/document/d/1M2zWWLp_5wn6OTN5kFqxbj8BVAO0UiEe1BP0nraieuc/edit?usp=sharing) to take notes in - it contains the hangout link, too. (Prior to the meeting, feel free to add links, questions, thoughts etc in appropriate places.)

Looking forward to catching up with you all!

Phil

**Comment by jhrlsst** [comment]
How can I join the editorial meeting on Weds August 3rd at 0800 PDT?
Is there a bluejean number?

**Comment by StephenRidgway** [comment]
Sorry I will be away from internet and could not find an associated telephone number.

I read that each participant can add one by telephone number - if so, somebody could call me at 520-248-4408, might work.

Steve

**Comment by drphilmarshall** [comment]
Morning all!

Looking forward to meeting in a bit under half an hour.  We'll meet in the usual LSST Google hangout - the link is in [this Google doc](https://docs.google.com/document/d/1M2zWWLp_5wn6OTN5kFqxbj8BVAO0UiEe1BP0nraieuc/edit?usp=sharing), and we'll use that to take notes in as well. 

See you soon!

Phil

**Comment by ivezic** [comment]
Yes, we can use
http://ls.st/zih

**Comment by AshishMahabal** [comment]
Hi, Jeonghee,

The hangout link is included in the doc: https://docs.google.com/document/d/1M2zWWLp_5wn6OTN5kFqxbj8BVAO0UiEe1BP0nraieuc/edit#heading=h.fhdcgdiqpm5p <https://docs.google.com/document/d/1M2zWWLp_5wn6OTN5kFqxbj8BVAO0UiEe1BP0nraieuc/edit#heading=h.fhdcgdiqpm5p>

-ashish

**Comment by drphilmarshall** [comment]
All: thanks for joining at today's meeting, and apologies for any connectivity issues! Note to self: Google hangouts can still only support 10 people at a time, and we won't always be lucky enough to get exactly 10 people attending...

I have tidied up our [notes](https://docs.google.com/document/d/1M2zWWLp_5wn6OTN5kFqxbj8BVAO0UiEe1BP0nraieuc/edit#) and issued the chapter editors with getting the science section summaries issued and chapter summaries started. All the editorial work is now issued too, and I will be working on that between now and Tucson. Thanks for all your input, and your work in the next few weeks! We agreed that Weds August 31 was a reasonable deadline for submitting the white paper to the pub board for review, after working hard on getting it up to conference proceedings standard between now and then (not to mention working on it during the meeting). 

Thanks again for all your hard work!
